### ISSUE TITLE
Command-sending fails to auto-connect.

### ISSUE THREAD

**Issue by nickovs** [thecynic/pylutron#17]
The `LutronConnection.send()` method doesn't call `_maybe_reconnect()` and as a result if it is called and the connection has dropped an attribute error exception is raised because `None` has no `write()` method (see the stack trace below from Home Assistant). As it stands there can't just be a `_maybe_reconnect()` in the send method because it gets called from `_do_login()` but if might be good to move the existing code to a `_send()` method (which *can* be called from `_do_login()`) and then have the public `send()` method call `_maybe_reconnect()` before calling that code.

On a related note, at the moment `_maybe_reconnect()` only spots if the socket has already been marked as closed and the `_connected` flag reset. If the flag is set then it might be worth checking if the socket is actually still alive before trying to use it, to avoid the client code needing to manually retry failed requests. This can be done by calling `recv()` on the underlying socket passing the `socket.MSG_DONTWAIT | socket.MSG_PEEK` as the flags, to see if there is anything there. If this raises a `BlockingIOError` then the socket is alive, if it returns data then the socket is probably alive and if it returns an empty bytes object then the socket has been closed and you need to call `_disconnect()` and then reconnect.

```
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/core.py", line 1038, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/components/light/__init__.py", line 362, in async_handle_light_service
    await light.async_turn_off(**params)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/components/light/lutron.py", line 74, in turn_off
    self._lutron_device.level = 0
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/pylutron/__init__.py", line 485, in level
    Output.ACTION_ZONE_LEVEL, "%.2f" % new_level)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/pylutron/__init__.py", line 324, in send
    self._conn.send(op + out_cmd)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/pylutron/__init__.py", line 69, in send
    self._telnet.write(cmd.encode('ascii') + b'\r\n')
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by JuanitoAlimana** [comment]
I can’t log in to iTunes anymore

**Comment by thecynic** [comment]
Think this is resolved with latest connection management improvements.

**Comment by DanskerUS** [comment]
I am still seeing failure to reconnect. Power off repeater, back on, or cycle power to eth switch, or temporarily unplug repeater RJ-45, then HA reconnects after reboot only.

**Comment by amattas** [comment]
Home Assistant 0.101.3

**Comment by Tadimsky** [comment]
I've been seeing this a lot recently in Home Assistant too.

**Comment by amattas** [comment]
I just updated more information in https://github.com/home-assistant/home-assistant/issues/29642 It's still happening in 0.103.6

**Comment by JonGilmore** [comment]
> Ya'll wanna see if #48 solves your problem?

Tested this quickly this morning and it doesn't seem to have any impact. If you power cycle the ra2 main repeater while HA is up, it still doesn't reconnect.

**Comment by thecynic** [comment]
I commented on 29642.

@JonGilmore so it's happening to you too? Back when I pushed 0.2.5, you tested it and things were working for you. Has this regressed for you too then?

**Comment by thecynic** [comment]
GNET> ?SYSTEM,8
OS Firmware Revision = 10.6.0 [Nov 01 2016 05:48:45]

**Comment by JonGilmore** [comment]
Certainly appears to have. My recent testing has been flakey at best. I got it to reconnect and work once within HomeAssistant, but all other times, it has failed. TBH, I can't remember when I upgraded my repeater fw, but I'm now on 12, maybe that impacted things? 

```
GNET> ?SYSTEM,8
OS Firmware Revision = 12.0.0 [Sep 21 2017 09:50:12]
```

**Comment by JuanitoAlimana** [comment]
stop emails

**Comment by cdheiser** [comment]
> stop emails
> […](#)

You need to unsubscribe from the issue.

**Comment by JuanitoAlimana** [comment]
i have done millions of times

**Comment by cdheiser** [comment]
@JonGilmore is this still an issue?  I haven't experienced this problem in quite some time.

**Comment by amattas** [comment]
Timely, we had a power hiccup this evening and it still caused an issue for me. I haven’t had a chance to hunt down logs yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JonGilmore** [comment]
@cdheiser I haven't personally witnessed this on my system in a _very_ long time, but I will say that my power and network is extremely stable.

**Comment by cdheiser** [comment]
I've been spending the week getting around to replacing the rest of my non-smart switches this week and thus updating the repeater multiple times and the connection is consistently coming back fine.  I've only needed to restart home assistant to pull updated XML.

**Comment by amattas** [comment]
So I forgot that the log file rolls over on reboot – so I can’t find the trace of what happened, I’m going to try to re-create it this week.

Anthony Mattas

***@***.******@***.***>
m: +1 (513) 549-5829

From: cdheiser ***@***.***>
Reply-To: thecynic/pylutron ***@***.***>
Date: Friday, July 16, 2021 at 10:56 PM
To: thecynic/pylutron ***@***.***>
Cc: Anthony Mattas ***@***.***>, Comment ***@***.***>
Subject: Re: [thecynic/pylutron] Command-sending fails to auto-connect. (#17)


I've been spending the week getting around to replacing the rest of my non-smart switches this week and thus updating the repeater multiple times and the connection is consistently coming back fine. I've only needed to restart home assistant to pull updated XML.

**Comment by JonGilmore** [comment]
Thanks - let us know what you come up with in your testing. 

Also, just an FYI @amattas - your phone number is on your signature when you replied to this, so it showed up on your comment. I deleted it, but people can still view the comment and see the edit. just wanted you to be aware :D

**Comment by amattas** [comment]
Happened again tonight, aside from the unknown device – I have no idea what caused it.


***@***.***:/opt/homeassistant$ cat home-assistant.log | grep --text lutron

2021-07-16 22:04:03 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'tts', 'logbook', 'ifttt', 'zwave_js', 'updater', 'ios', 'zone', 'conversation', 'automation', 'group', 'ffmpeg', 'discovery', 'zeroconf', 'blueprint', 'panel_iframe', 'network', 'device_tracker', 'trace', 'notify', 'switch', 'lutron', 'homekit', 'camera', 'map', 'sun', 'system_health', 'history', 'sonos', 'script'}

2021-07-16 22:04:03 INFO (MainThread) [homeassistant.setup] Setting up lutron

2021-07-16 22:04:13 WARNING (MainThread) [homeassistant.setup] Setup of lutron is taking over 10 seconds.

2021-07-16 22:04:27 INFO (SyncWorker_0) [pylutron] Loaded xml db from repeater

2021-07-16 22:04:27 INFO (SyncWorker_0) [pylutron] Found Lutron project: Project, 22 areas

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Started

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Connecting

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Connected

2021-07-16 22:04:27 INFO (SyncWorker_0) [homeassistant.components.lutron] Connected to main repeater at 10.0.0.10

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,12,2)

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,255,2)

2021-07-16 22:04:27 INFO (MainThread) [homeassistant.setup] Setup of domain lutron took 24.2 seconds

2021-07-16 22:04:27 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.lutron

2021-07-16 22:04:27 INFO (MainThread) [homeassistant.components.cover] Setting up cover.lutron

2021-07-16 22:04:27 INFO (MainThread) [homeassistant.components.switch] Setting up switch.lutron

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,3,1)

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,4,1)

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,5,1)

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,6,1)

2021-07-16 22:04:27 INFO (Thread-3) [pylutron] Unknown cmd MONITORING (~MONITORING,8,1)

2021-07-16 22:04:29 INFO (MainThread) [homeassistant.components.light] Setting up light.lutron

2021-07-16 22:04:29 INFO (MainThread) [homeassistant.components.scene] Setting up scene.lutron

2021-07-16 22:13:44 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,3)

2021-07-17 06:55:11 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,4)

2021-07-17 21:17:57 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,3)

2021-07-18 06:43:13 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,4)

2021-07-18 15:01:57 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,3)

2021-07-18 15:05:28 INFO (SyncWorker_13) [homeassistant.loader] Loaded lutron_caseta from homeassistant.components.lutron_caseta

2021-07-18 19:27:12 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,4)

2021-07-18 23:25:42 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,3)

2021-07-19 06:59:16 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,4)

2021-07-19 16:41:59 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,32,3)

2021-07-19 19:35:17 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,32,4)

2021-07-20 00:40:26 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,3)

2021-07-20 06:50:15 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,4)

2021-07-20 21:37:39 WARNING (Thread-3) [pylutron] Unknown id 21 (~DEVICE,21,33,3)


Anthony Mattas

From: Jon Gilmore ***@***.***>
Reply-To: thecynic/pylutron ***@***.***>
Date: Sunday, July 18, 2021 at 10:12 AM
To: thecynic/pylutron ***@***.***>
Cc: Anthony Mattas ***@***.***>, Mention ***@***.***>
Subject: Re: [thecynic/pylutron] Command-sending fails to auto-connect. (#17)


Thanks - let us know what you come up with in your testing.

Also, just an FYI @amattas<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famattas&data=04%7C01%7Canthony%40mattas.net%7C76c0837188db42d139bd08d949f61543%7C20e5b14899e942519006662b26413b94%7C1%7C0%7C637622143553349557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AH9JiRuQlHRu3v93qS24VEMIUi26v4La0aZLjDDS5QU%3D&reserved=0> - your phone number is on your signature when you replied to this, so it showed up on your comment. I deleted it, but people can still view the comment and see the edit. just wanted you to be aware :D

**Comment by cdheiser** [comment]
Anthony,

Can you post your DbXmlInfo.xml from the main repeater somewhere?  It will
both tell us what ID 21 is and what version of the firmware you are using.

**Comment by cdheiser** [comment]
Note I had problems too yesterday and debugged it to the main repeater
taking 10+ minutes to start accepting logins on the telnet port again.
Just waiting long enough resolved the problem.

**Comment by JonGilmore** [comment]
@cdheiser I feel like what you're describing is a bug on the repeater that I remember reading about on the lutron forums, but I'm struggling to find the thread.

**Comment by cdheiser** [comment]
Yeah, it used to be that you had to reboot the repeater to fix it.  I'm
running 12.8.0.  I can't see any additional fixes/improvements in 12.9 or
12.10 so I haven't upgraded.

**Comment by cdheiser** [comment]
After tearing my hair out trying to get a firmware update to go through,
I've moved on to 12.10 and everything came back flawlessly, no delays, no
errors.

**Comment by amattas** [comment]
I have a dual repeater system, and the multicast packets never seem to traverse the network properly, so I have to upgrade both using empty projects – and then sometimes stuff just breaks, it’s my biggest frustration.


From: cdheiser ***@***.***>
Reply-To: thecynic/pylutron ***@***.***>
Date: Thursday, July 29, 2021 at 12:36 AM
To: thecynic/pylutron ***@***.***>
Cc: Anthony Mattas ***@***.***>, Mention ***@***.***>
Subject: Re: [thecynic/pylutron] Command-sending fails to auto-connect. (#17)

After tearing my hair out trying to get a firmware update to go through,
I've moved on to 12.10 and everything came back flawlessly, no delays, no
errors.

**Comment by cdheiser** [comment]
You can switch to unicast and it might work better.  My problem is it
completely fails unless I assign a static ip address.

**Comment by amattas** [comment]
Unicast works for config changes, but multicast is required for firmware upgrades. smh

From: cdheiser ***@***.***>
Reply-To: thecynic/pylutron ***@***.***>
Date: Thursday, July 29, 2021 at 1:35 PM
To: thecynic/pylutron ***@***.***>
Cc: Anthony Mattas ***@***.***>, Mention ***@***.***>
Subject: Re: [thecynic/pylutron] Command-sending fails to auto-connect. (#17)

You can switch to unicast and it might work better. My problem is it
completely fails unless I assign a static ip address.

**Comment by cdheiser** [comment]
This is obsolete.  If people have connection problems, please open a new issue.  The library now uses telnetlib3
